# k-mer length/minimum read trim length
k: 31

# genome length
L: 2000000

# multinomial probabilities for generating genome
pA: 0.25

pC: 0.25

pG: 0.25

pT: 0.25

# unqualified_percent_limit for fastp: how many percents of bases are allowed to be unqualified in terms of quality score
unqualLimit: 40

# quality score for read trimming
qualThresh: 30

# window length for read trimming
windowLength: 1

# minimum k-mer count threshold
mincount: 3

# maximum k-mer count recorded
maxcount: 1000000

# e-value for blast
blastEvalue: 0.0000000001

# species
species:
 - "GCA_000180655.1_ASM18065v1_genomic"
 - "GCA_000340665.3_Cajca.Asha_v2.0_genomic"
