# k-mer length/minimum read trim length

# quality threshold for dropping reads

# quality score for read trimming

# window length for read trimming

# minimum k-mer count threshold
mincount: 5

# e-value for blast