$schema: "https://json-schema.org/draft/2020-12/schema"
description: parameters that can vary for each simulation
properties:
  rep:
    type: number
    description: replicate of simulation
  N:
    type: integer
    description: population size for single population simulations
  n:
    type: integer
    description: sample size
  sigma:
    type: number
    description: selfing rate
  mu:
    type: number
    description: mutation rate per base pair per generation per type of nucleotide transition
  R:
    type: number
    description: recombination rate per base per generation
  cov:
    type: number
    description: total sequencing coverage
  L:
    type: integer
    description: genome length
  sequencer:
    type: string
    description: type sequencing instrument to simulate
  simtype:
    type: string
    description: SLiM simlation to perform
  shape:
    type: number
    description: shape parameter for zeta distribution
  shuffle:
    type: boolean
    description: whether k-mers should be shuffled to make ancestral genome
  pA:
    type: number
    description: probability of sampling A
    minimum: 0
    maximum: 1
  pC:
    type: number
    description: probability of sampling C
    minimum: 0
    maximum: 1
  pG:
    type: number
    description: probability of sampling G
    minimum: 0
    maximum: 1
  pT:
    type: number
    description: probability of sampling T
    minimum: 0
    maximum: 1
  N1:
    type: integer
    description: number of individuals in population split
  N2:
    type: integer
  mg1:
    type: number
  mg2:
    type: number
  tau:
    type: integer
  h:
    type: number
  Nes:
    type: number
  s:
    type: number
  qtl_mean:
    type: number
  qtl_sigma:
    type: number
  qtl_prop:
    type: number
  optimum_mean:
    type: number
  optimum_sigma:
    type: number
  phenotype_cutoff:
    type: number
  ID:
    type: string
