$schema: "https://json-schema.org/draft/2020-12/schema"
description: parameters that can vary for each simulation
properties:
  rep:
    type: number
    description: replicate of simulation
  N:
    type: integer
    description: population size for single population simulations
  n:
    type: integer
    description: sample size
  mu:
    type: number
    description: mutation rate per base pair per generation per type of nucleotide transition
  R:
    type: number
    description: recombination rate per base per generation
  cov:
    type: number
    description: total sequencing coverage
  sequencer:
    type: string
    description: type sequencing instrument to simulate
  simtype:
    type: string
    description: SLiM simlation to perform
  shape:
    type: number
    description: shape parameter for zeta distribution
  shuffle:
    type: boolean
    description: whether k-mers should be shuffled to make ancestral genome
  Nes:
    type: number
    description: scaled selection coefficient of sweep
  s:
    type: number
    description: selection coefficient
  ID:
    type: string
    description: unique identifier for each simulation
