executor: slurm
jobs: 975
cores: 975

# use sensible defaults for your cluster
default-resources:
    slurm_account: "josephsnodes"
    slurm_partition: "josephsnodes"
    mem_mb_per_cpu: 8000
    cpus_per_task: 1
    runtime: "239m"

# rules to execute locally, because they're too fast to bother with cluster submission
#localrules: all_one_pops, all_two_pops

# here only rules, which require different (more) resources:
set-resources:
    bwa_one_pop:
        cpus_per_task: 2
    bwa_two_pop:
        cpus_per_task: 2
    iss_one_pop:
        cpus_per_task: 4
    iss_two_pop:
        cpus_per_task: 4

# parallelization with threads needs to be defined separately:
# threads and cpus_per_task are supposed to be synonymous for this plugin, but for some reason I need to specify them separately
set-threads:
    bwa_one_pop: 2
    bwa_two_pop: 2
    iss_one_pop: 4
    iss_two_pop: 4
