executor: slurm
jobs: 975
cores: 975

# use sensible defaults for your cluster

default-resources:
    slurm_account: "josephsnodes"
    slurm_partition: "josephsnodes"
    mem_mb_per_cpu: 8000
    cpus_per_task: 1
    runtime: "239m"

# here only rules, which require different (more) resources:
#set-resources:
#    rule_a:
#        runtime: "2h"

#    rule_b:
#        mem_mb_per_cpu: 3600
#        runtime: "5h"

# parallelization with threads needs to be defined separately:
set-threads:
    bwa_one_pop: 2
    bwa_two_pop: 2
    iss_one_pop: 4
    iss_two_pop: 4
